title: "Yunzhi (Ariel) Zheng"
author: "Yunzhi (Ariel) Zheng"
email: "yzheng9@fsu.edu"
description: "Couple Relationships · Mindfulness · Dyadic Processes · Machine Learning for Psychotherapy"


url: "https://yunzhiarielzheng.github.io"
baseurl: ""  

# ---- Theme ----
theme: minima

# ---- Plugins supported by GitHub Pages ----
plugins:
  - jekyll-feed
  - jekyll-sitemap

# ---- Navigation (top menu) ----

header_pages:
  - presentations.md
  - publications.md
  - teaching.md
  - clinical.md
